name: Linux Build
on:
  push:
    branches:
      - devops
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://torchextentionbuilder/manylinux:py${{ matrix.python }}-cu${{ matrix.cuda }}
    strategy:
      fail-fast: false
      matrix:
        cuda: [10.2, 11.3]
        python: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Env Check
        run: |
          echo $TORCH_CUDA_ARCH_LIST
          echo $TORCH_LIBRARY_PATH
          echo $LD_LIBRARY_PATH
          ls -l /usr/local

      - name: Build Wheel
        run: python $GITHUB_WORKSPACE/setup.py bdist_wheel
        
      - name: Repair Wheel
        run: auditwheel repair $GITHUB_WORKSPACE/dist/*.whl --plat manylinux_2_17_x86_64 --only-plat
        
      - name: Patch Wheel
        run: torchdist $GITHUB_WORKSPACE/wheelhouse/*manylinux*.whl

      - name: Publish Package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: torchdist/
