name: Build

on:
  push:
    branches:
      - devops

jobs:

  build-wheels:
    name: Build Wheels
    uses: charliebudd/torch-extention-builder/.github/workflows/build-pytorch-extention-wheels.yml@main
    with:
        python-versions: "[3.6, 3.7, 3.8]"
        pytorch-versions: "[1.9, '1.10']"
        cuda-versions: "[10.2, 11.3]"

  publish-wheels:
    name: Publish Wheels
    runs-on: ubuntu-latest
    needs: build-wheels
    steps:
      - name: Download Cached Wheels
        uses: actions/download-artifact@v3
        with:
          name: final-wheels
          path: dist

      - name: Publish Package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          