name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-wheels:
    name: Build Wheels
    uses: charliebudd/torch-extension-builder/.github/workflows/build-pytorch-extension-wheels.yml@version-tagging

  test-wheels-locally:
    name: Test Wheels Locally
    needs: build-wheels
    uses: ./.github/workflows/test.yml
    with:
      local-wheels: true
      wheel-location: final-wheels
      python-versions: "[3.6, 3.7, 3.8, 3.9]"
      pytorch-versions: "[1.9, '1.10', 1.11]"
      cuda-versions: "[10.2, 11.3]"

  publish-wheels-to-testpypi:
    name: Publish Wheels To TestPyPI
    runs-on: ubuntu-latest
    needs: test-wheels-locally
    steps:
      - name: Download Cached Wheels
        uses: actions/download-artifact@v3
        with:
          name: final-wheels
          path: dist

      - name: Publish Package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  test-testpypi-release:
    name: Test TestPyPi Release
    needs: publish-wheels-to-testpypi
    uses: ./.github/workflows/test.yml
    with:
      local-wheels: false
      wheel-location: https://test.pypi.org/simple/
      python-versions: "[3.6, 3.7, 3.8, 3.9]"
      pytorch-versions: "[1.9, '1.10', 1.11]"
      cuda-versions: "[10.2, 11.3]"
