name: Build

on:
  push:
    branches:
      - devops

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: pwd
      # - run: ls
      # - run: ls torch-content-area
      - uses: ./.github/actions/build-cu11.3
