name: Build

on: push

jobs: 
  update-readme:
    name: Test Release
    runs-on: [self-hosted, Linux, X64, gpu]
    strategy:
      fail-fast: false
      matrix:
        python: [3.9]
        pytorch: [1.11]
        cuda: [11.3]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install Test Requirements
        run: |
          ENV=../.venv-${{ matrix.python }}-${{ matrix.pytorch }}-${{ matrix.cuda }}
          if [ -d "$ENV" ]; then
            . $ENV/bin/activate
          else
            python -m venv $ENV
            . $ENV/bin/activate
            python -m pip install -U --force-reinstall pip
            python -m pip install numpy pillow torch==${{ matrix.pytorch }} -f https://download.pytorch.org/whl/cu$(echo ${{ matrix.cuda }} | sed 's/\.//')/torch_stable.html
          fi

          python -V
          pip show torch
        
      - name: Install torchcontentarea
        run: python setup.py install

      - id: run-tests
        name: Run Tests
        run: |
          RESULTS=$(python testing/test_performance.py | grep '-')
          RESULTS=$(printf '%s\n' "$RESULTS" | sed 's/\\/&&/g;s/^[[:blank:]]/\\&/;s/$/\\/')

          START="<!-- performance stats start -->"
          END="<!-- performance stats end -->"
          sed -ni "/$START/{p;:a;N;/$END/!ba;s/.*\n/$RESULTS \n/};p" README.md

          cat README.md

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
